name: Docker

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:
    name: Build
    uses: dargmuesli/github-actions/.github/workflows/docker.yml@0.20.0
    secrets:
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      DOCKER_HUB_USER_NAME: ${{ secrets.DOCKER_HUB_USER_NAME }}
    with:
      ARCHITECTURES: linux/arm64/v8,linux/amd64
